source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Test_Swift' do
    platform :ios, '11.0'
    
    pod 'AppStoreRatings', :git => 'https://github.com/AjuntamentdeBarcelona/osam-valoracions-ios', :tag => '1.0.1'
end
